name: Grafana Alloy
version: "1.0.2"
slug: grafana_alloy
description: Scrape the Home Assistant Prometheus endpoint and remote-write metrics to Grafana Cloud using Grafana Alloy.
url: https://github.com/petergreen86/ha-grafana-alloy/tree/main/grafana_alloy
arch:
  - amd64
  - aarch64
init: false
homeassistant_api: true
ingress: true
ingress_port: 12345
panel_icon: mdi:chart-line
panel_title: Alloy
options:
  prometheus_url: ""
  prometheus_username: ""
  api_key: ""
  scrape_interval: "60s"
schema:
  prometheus_url: url
  prometheus_username: str
  api_key: password
  scrape_interval: str
